CREATE TABLE restaurant (
    id UUID PRIMARY KEY,
    name VARCHAR NOT NULL,
    photo VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);